version: '3'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    mem_limit: 512m
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "61616:61616"   # Port für JMS
      - "8161:8161"     # Port für das ActiveMQ-Webinterface
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - efd-generator_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"     # Standard-Port für Redis
    networks:
      - efd-generator_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  efd_generator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - activemq
      - redis
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
    volumes:
      - efd_data:/app/data  # Volumen zur Speicherung der EFD-Meldungen
    networks:
      - efd-generator_network
    restart: unless-stopped
    deploy:
      replicas: 3  # 3 Container für den EFD-Generator

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    ports:
      - "9091:9091"  # Port für den Load Balancer
      - "1936:1936"  # Port für das HAProxy-Webinterface
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # Konfigurationsdatei für HAProxy
    restart: unless-stopped
    networks:
      - efd-generator_network
    depends_on:
      - efd_generator
      - activemq
    healthcheck:
      test: ["CMD-SHELL", "echo  'Contents:\nTEST\n12545\nTest Message\n'  | nc localhost 9090 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  efd_data:

networks:
  efd-generator_network:
    driver: bridge
