version: '3'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    mem_limit: 512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "61616:61616"   # Port für JMS
      - "8161:8161"     # Port für das ActiveMQ-Webinterface
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - efd-generator_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"     # Standard-Port für Redis
    networks:
      - efd-generator_network

  efd_generator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - activemq
      - redis
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
    volumes:
      - efd_data:/app/data  # Volumen zur Speicherung der EFD-Meldungen
    networks:
      - efd-generator_network
    deploy:
      replicas: 3  # 3 Container für den EFD-Generator

  # Load Balancer (HAProxy)
  load_balancer:
    image: haproxy:lts
    ports:
      - "9091:9091"  # Port für den Load Balancer
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # Konfigurationsdatei für HAProxy
    networks:
      - efd-generator_network
    depends_on:
      - efd_generator

volumes:
  efd_data:

networks:
  efd-generator_network:
    driver: bridge
